"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import Sidebar from "@/components/sidebar";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CustomPagination } from "@/components/CustomPagination";
import { createAcademicYear, createOffering, createSemester, getCalendarData, saveAcademicYear, saveSemester, updateOffering } from "./actions";

type CalendarData = { years: any[]; semesters: any[]; courses: any[]; offerings: any[] };
type DialogKind = "year" | "semester" | "offering" | null;
const emptyData: CalendarData = { years: [], semesters: [], courses: [], offerings: [] };
const OFFERING_PAGE_SIZE = 8;

function campusInstant(value: string) {
  const approximateUtc = new Date(`${value}:00Z`);
  const offset = new Intl.DateTimeFormat("en", { timeZone: "Africa/Cairo", timeZoneName: "longOffset" }).formatToParts(approximateUtc).find((part) => part.type === "timeZoneName")?.value ?? "GMT+02:00";
  const match = offset.match(/GMT([+-])(\d{2}):(\d{2})/);
  const minutes = match ? (Number(match[2]) * 60 + Number(match[3])) * (match[1] === "+" ? 1 : -1) : 120;
  return new Date(approximateUtc.getTime() - minutes * 60000).toISOString();
}

function campusInput(value?: string) {
  if (!value) return undefined;
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Africa/Cairo", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value)).reduce<Record<string, string>>((result, part) => { result[part.type] = part.value; return result; }, {});
  return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;
}

function Field({ label, name, type = "text", required = true, placeholder, defaultValue }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string; defaultValue?: string }) {
  return <label className="grid min-w-0 gap-1.5 text-sm font-medium text-slate-700">{label}<Input name={name} type={type} required={required} placeholder={placeholder} defaultValue={defaultValue} /></label>;
}
function EmptyState({ children }: { children: ReactNode }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-5 py-10 text-center text-sm text-slate-500">{children}</div>; }
function PanelHeader({ description, action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="mb-4 flex min-w-0 flex-wrap items-end justify-between gap-3">{description && <div className="min-w-0"><p className="text-sm text-slate-500">{description}</p></div>}{action && <div className="shrink-0">{action}</div>}</div>; }
function DateBlock({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-lg bg-slate-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 break-words text-slate-700">{value}</p></div>; }

export function AcademicCalendarManager() {
  const [data, setData] = useState<CalendarData>(emptyData);
  const [yearId, setYearId] = useState(""); const [semesterId, setSemesterId] = useState(""); const [courseId, setCourseId] = useState("");
  const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("semesters");
  const [offeringSearch, setOfferingSearch] = useState(""); const [offeringPage, setOfferingPage] = useState(1);
  const [dialog, setDialog] = useState<DialogKind>(null); const [editingYear, setEditingYear] = useState<any>(null); const [editingSemester, setEditingSemester] = useState<any>(null);
  const refresh = async () => { setLoading(true); try { const result = await getCalendarData(); if (result.success) { setData(result as CalendarData); if (!yearId && result.years?.[0]) setYearId(String(result.years[0].id)); if (!semesterId && result.semesters?.[0]) setSemesterId(String(result.semesters[0].id)); if (!courseId && result.courses?.[0]) setCourseId(String(result.courses[0].course_id)); } else setNotice(result.error ?? "Could not load calendar data."); } finally { setLoading(false); } };
  // Load once on mount; refresh intentionally reads the initial selections.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void refresh(); }, []);
  const openCreate = (kind: Exclude<DialogKind, null>) => { setEditingYear(null); setEditingSemester(null); setNotice(""); setDialog(kind); };
  const closeDialog = () => { if (!busy) setDialog(null); };
  const run = async (event: FormEvent<HTMLFormElement>, callback: (form: FormData) => Promise<any>) => { event.preventDefault(); setBusy(true); setNotice(""); try { const result = await callback(new FormData(event.currentTarget)); if (!result.success) { setNotice(result.error ?? "Unable to save changes."); return; } setDialog(null); setEditingYear(null); setEditingSemester(null); setNotice("Saved successfully."); await refresh(); } catch { setNotice("Unable to save changes."); } finally { setBusy(false); } };
  const toggleSemester = async (semester: any) => { setBusy(true); setNotice(""); try { const result = await saveSemester(semester.id, { name: semester.name, startsAt: semester.startsAt, endsAt: semester.endsAt, registrationOpensAt: semester.registrationOpensAt, registrationClosesAt: semester.registrationClosesAt, addDropOpensAt: semester.addDropOpensAt, addDropClosesAt: semester.addDropClosesAt, isPublished: !semester.isPublished }); setNotice(result.success ? "Semester publication updated." : result.error ?? "Update failed."); await refresh(); } finally { setBusy(false); } };
  const toggleOffering = async (offering: any) => { setBusy(true); setNotice(""); try { const result = await updateOffering(offering.offeringId, { capacity: offering.capacity, isPublished: !offering.isPublished }); setNotice(result.success ? "Offering visibility updated." : result.error ?? "Update failed."); await refresh(); } finally { setBusy(false); } };
  const dialogTitle = dialog === "year" ? (editingYear ? "Edit academic year" : "Add academic year") : dialog === "semester" ? (editingSemester ? "Edit semester" : "Create semester") : "Create course offering";
  const filteredOfferings = useMemo(() => {
    const query = offeringSearch.trim().toLowerCase();
    if (!query) return data.offerings;

    return data.offerings.filter((offering) =>
      [offering.courseCode, offering.courseName, offering.academicYearName, offering.semesterName, offering.phase]
        .filter(Boolean)
        .some((value) => String(value).toLowerCase().includes(query)),
    );
  }, [data.offerings, offeringSearch]);
  const offeringTotalPages = Math.max(1, Math.ceil(filteredOfferings.length / OFFERING_PAGE_SIZE));
  const visibleOfferingPage = Math.min(offeringPage, offeringTotalPages);
  const paginatedOfferings = useMemo(
    () => filteredOfferings.slice((visibleOfferingPage - 1) * OFFERING_PAGE_SIZE, visibleOfferingPage * OFFERING_PAGE_SIZE),
    [filteredOfferings, visibleOfferingPage],
  );
  const tabs = <nav className="flex min-w-max gap-6 overflow-x-auto"><button onClick={() => setActiveTab("years")} className={`flex items-center gap-2 border-b-2 px-1 py-2 text-sm font-medium ${activeTab === "years" ? "border-blue-900 text-blue-900" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}`}>Academic Years ({data.years.length})</button><button onClick={() => setActiveTab("semesters")} className={`flex items-center gap-2 border-b-2 px-1 py-2 text-sm font-medium ${activeTab === "semesters" ? "border-blue-900 text-blue-900" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}`}>Semesters ({data.semesters.length})</button><button onClick={() => setActiveTab("offerings")} className={`flex items-center gap-2 border-b-2 px-1 py-2 text-sm font-medium ${activeTab === "offerings" ? "border-blue-900 text-blue-900" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}`}>Offerings ({data.offerings.length})</button></nav>;
  return <div className="flex min-h-screen bg-slate-50"><Sidebar /><main className="min-w-0 flex-1 overflow-x-hidden p-4 sm:p-6 lg:p-8"><PageHeader title="Academic Calendar" description="Manage academic years, registration windows, and course offerings" tabs={tabs} /><div className="mx-auto min-w-0 max-w-7xl space-y-5 pt-4">{notice && <p role="status" className="rounded-lg border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-900">{notice}</p>}{loading ? <EmptyState>Loading calendar data…</EmptyState> : <>
    {activeTab === "years" && <div className="min-w-0 space-y-4"><PanelHeader title="Academic years" description="Define the academic year boundaries." action={<Button onClick={() => openCreate("year")}>Add academic year</Button>} />{data.years.length ? <div className="divide-y divide-slate-200 rounded-xl border border-slate-200 bg-white">{data.years.map((year) => <div key={year.id} className="flex min-w-0 flex-wrap items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="font-medium text-slate-900">{year.name}</p><p className="text-sm text-slate-500">{new Date(year.startsAt).toLocaleDateString()} – {new Date(year.endsAt).toLocaleDateString()}</p></div><Button type="button" variant="outline" size="sm" onClick={() => { setEditingYear(year); setNotice(""); setDialog("year"); }}>Edit</Button></div>)}</div> : <EmptyState>No academic years yet. Add one to create semesters.</EmptyState>}</div>}
    {activeTab === "semesters" && <div className="min-w-0 space-y-4"><PanelHeader title="Semesters and registration windows" description="Set term dates and Cairo registration windows." action={<Button disabled={!data.years.length} onClick={() => openCreate("semester")}>Add semester</Button>} />{!data.years.length && <p className="mb-4 text-sm text-amber-700">Create an academic year before adding a semester.</p>}{data.semesters.length ? <div className="grid min-w-0 gap-4 lg:grid-cols-2">{data.semesters.map((semester) => <article key={semester.id} className="min-w-0 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold text-slate-900">{semester.academicYearName} {semester.name}</h3><p className="text-sm text-slate-500">{semester.phase} · {semester.isPublished ? "Published" : "Draft"}</p></div><div className="flex shrink-0 flex-wrap gap-2"><Button variant="outline" size="sm" disabled={busy} onClick={() => { setEditingSemester(semester); setYearId(String(semester.academicYearId)); setNotice(""); setDialog("semester"); }}>Edit</Button><Button variant="outline" size="sm" disabled={busy} onClick={() => void toggleSemester(semester)}>{semester.isPublished ? "Unpublish" : "Publish"}</Button></div></div><div className="mt-4 grid min-w-0 gap-3 text-sm sm:grid-cols-3"><DateBlock label="Term dates" value={`${new Date(semester.startsAt).toLocaleDateString()} – ${new Date(semester.endsAt).toLocaleDateString()}`} /><DateBlock label="Registration (Cairo)" value={`${new Date(semester.registrationOpensAt).toLocaleString()} – ${new Date(semester.registrationClosesAt).toLocaleString()}`} /><DateBlock label="Add/drop (Cairo)" value={`${new Date(semester.addDropOpensAt).toLocaleString()} – ${new Date(semester.addDropClosesAt).toLocaleString()}`} /></div></article>)}</div> : <EmptyState>No semesters yet.</EmptyState>}</div>}
    {activeTab === "offerings" && <div className="min-w-0 space-y-4">{(!data.courses.length || !data.semesters.length) && <p className="mb-4 text-sm text-amber-700">Add at least one course and semester before creating an offering.</p>}<div className="flex flex-wrap items-center gap-3 p-4"><Input className="w-full sm:max-w-md" value={offeringSearch} onChange={(event) => { setOfferingSearch(event.target.value); setOfferingPage(1); }} placeholder="Search course offerings..." aria-label="Search course offerings" /><Button className="ml-auto" disabled={!data.courses.length || !data.semesters.length} onClick={() => openCreate("offering")}>Add offering</Button></div>{filteredOfferings.length ? <div className="min-w-0 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-slate-500"><tr><th className="p-4">Course</th><th className="p-4">Semester</th><th className="p-4">Enrollment</th><th className="p-4">Capacity</th><th className="p-4">Phase</th><th className="p-4">Visibility</th></tr></thead><tbody className="divide-y divide-slate-200">{paginatedOfferings.map((offering) => <tr key={offering.offeringId}><td className="max-w-xs break-words p-4 font-medium text-slate-900">{offering.courseCode} · {offering.courseName}</td><td className="p-4">{offering.academicYearName} {offering.semesterName}</td><td className="p-4">{offering.enrollmentCount}</td><td className="p-4">{offering.capacity}</td><td className="p-4">{offering.phase}</td><td className="p-4"><Button variant="outline" size="sm" disabled={busy} onClick={() => void toggleOffering(offering)}>{offering.isPublished ? "Unpublish" : "Publish"}</Button></td></tr>)}</tbody></table></div> : <EmptyState>{data.offerings.length ? "No course offerings match your search." : "No course offerings yet."}</EmptyState>}{filteredOfferings.length > 0 && <CustomPagination currentPage={visibleOfferingPage} pageSize={OFFERING_PAGE_SIZE} totalItems={filteredOfferings.length} onPageChange={setOfferingPage} />}</div>}</>}</div></main>
    <Dialog open={dialog !== null} onOpenChange={(open) => !open && closeDialog()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{dialogTitle}</DialogTitle><DialogDescription>{dialog === "year" ? "Set the academic year boundaries." : dialog === "semester" ? "Configure term dates and registration windows in Cairo time." : "Choose a catalog course, semester, capacity, and publication status."}</DialogDescription></DialogHeader>
      {dialog === "year" && <form key={editingYear?.id ?? "new-year"} className="grid gap-4 px-6 py-5 sm:grid-cols-3" onSubmit={(event) => run(event, (form) => { const request = { name: String(form.get("name")), startsAt: String(form.get("startsAt")), endsAt: String(form.get("endsAt")) }; return editingYear ? saveAcademicYear(editingYear.id, request) : createAcademicYear(request); })}><Field label="Name" name="name" placeholder="2026-2027" defaultValue={editingYear?.name} /><Field label="Starts" name="startsAt" type="date" defaultValue={editingYear?.startsAt?.slice(0, 10)} /><Field label="Ends" name="endsAt" type="date" defaultValue={editingYear?.endsAt?.slice(0, 10)} /><DialogFooter className="px-0 pb-0 sm:col-span-3"><Button type="button" variant="outline" onClick={closeDialog}>Cancel</Button><Button disabled={busy}>{editingYear ? "Save academic year" : "Add academic year"}</Button></DialogFooter></form>}
      {dialog === "semester" && <form key={editingSemester?.id ?? "new-semester"} className="grid max-h-[65vh] gap-5 overflow-y-auto px-6 py-5 sm:grid-cols-2" onSubmit={(event) => run(event, (form) => { const request = { name: String(form.get("name")), startsAt: String(form.get("startsAt")), endsAt: String(form.get("endsAt")), registrationOpensAt: campusInstant(String(form.get("registrationOpensAt"))), registrationClosesAt: campusInstant(String(form.get("registrationClosesAt"))), addDropOpensAt: campusInstant(String(form.get("addDropOpensAt"))), addDropClosesAt: campusInstant(String(form.get("addDropClosesAt"))), isPublished: form.get("isPublished") === "on" }; return editingSemester ? saveSemester(editingSemester.id, request) : createSemester(Number(yearId), request); })}><label className="grid gap-1.5 text-sm font-medium text-slate-700 sm:col-span-2">Academic year<select className="h-9 w-full rounded-md border border-blue-200 bg-white px-3 text-sm" value={yearId} onChange={(event) => setYearId(event.target.value)} required disabled={Boolean(editingSemester)}>{data.years.map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select></label><Field label="Semester name" name="name" placeholder="Fall" defaultValue={editingSemester?.name} /><Field label="Term starts" name="startsAt" type="date" defaultValue={editingSemester?.startsAt?.slice(0, 10)} /><Field label="Term ends" name="endsAt" type="date" defaultValue={editingSemester?.endsAt?.slice(0, 10)} /><Field label="Registration opens (Cairo)" name="registrationOpensAt" type="datetime-local" defaultValue={campusInput(editingSemester?.registrationOpensAt)} /><Field label="Registration closes (Cairo)" name="registrationClosesAt" type="datetime-local" defaultValue={campusInput(editingSemester?.registrationClosesAt)} /><Field label="Add/drop opens (Cairo)" name="addDropOpensAt" type="datetime-local" defaultValue={campusInput(editingSemester?.addDropOpensAt)} /><Field label="Add/drop closes (Cairo)" name="addDropClosesAt" type="datetime-local" defaultValue={campusInput(editingSemester?.addDropClosesAt)} /><label className="flex items-center gap-2 text-sm font-medium text-slate-700 sm:col-span-2"><input name="isPublished" type="checkbox" defaultChecked={editingSemester?.isPublished} className="size-4 accent-blue-900" /> Published</label><DialogFooter className="px-0 pb-0 sm:col-span-2"><Button type="button" variant="outline" onClick={closeDialog}>Cancel</Button><Button disabled={busy || !yearId}>{editingSemester ? "Save semester" : "Create semester"}</Button></DialogFooter></form>}
      {dialog === "offering" && <form className="grid gap-4 px-6 py-5" onSubmit={(event) => run(event, (form) => createOffering({ courseId: Number(courseId), semesterId: Number(semesterId), capacity: Number(form.get("capacity")), isPublished: form.get("isPublished") === "on" }))}><label className="grid gap-1.5 text-sm font-medium text-slate-700">Catalog course<select className="h-9 w-full rounded-md border border-blue-200 bg-white px-3 text-sm" value={courseId} onChange={(event) => setCourseId(event.target.value)} required>{data.courses.map((course) => <option key={course.course_id} value={course.course_id}>{course.course_code} · {course.course_name}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium text-slate-700">Semester<select className="h-9 w-full rounded-md border border-blue-200 bg-white px-3 text-sm" value={semesterId} onChange={(event) => setSemesterId(event.target.value)} required>{data.semesters.map((semester) => <option key={semester.id} value={semester.id}>{semester.academicYearName} {semester.name}</option>)}</select></label><Field label="Seat capacity" name="capacity" type="number" /><label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input name="isPublished" type="checkbox" className="size-4 accent-blue-900" /> Published</label><DialogFooter className="px-0 pb-0"><Button type="button" variant="outline" onClick={closeDialog}>Cancel</Button><Button disabled={busy || !semesterId || !courseId}>Create offering</Button></DialogFooter></form>}
      {notice && dialog && <p role="alert" className="px-6 pb-5 text-sm text-red-600">{notice}</p>}</DialogContent></Dialog>
  </div>;
}
